package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class AgentProfitSetting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_profit_settings.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_profit_settings.pay_channel_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer payChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_profit_settings.trade_type
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Byte tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_profit_settings.percent
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Float percent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_profit_settings.floor_number
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer floorNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_profit_settings.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_profit_settings.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_profit_settings.agent_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer agentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_profit_settings.id
     *
     * @return the value of agent_profit_settings.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_profit_settings.id
     *
     * @param id the value for agent_profit_settings.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_profit_settings.pay_channel_id
     *
     * @return the value of agent_profit_settings.pay_channel_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getPayChannelId() {
        return payChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_profit_settings.pay_channel_id
     *
     * @param payChannelId the value for agent_profit_settings.pay_channel_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setPayChannelId(Integer payChannelId) {
        this.payChannelId = payChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_profit_settings.trade_type
     *
     * @return the value of agent_profit_settings.trade_type
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Byte getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_profit_settings.trade_type
     *
     * @param tradeType the value for agent_profit_settings.trade_type
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setTradeType(Byte tradeType) {
        this.tradeType = tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_profit_settings.percent
     *
     * @return the value of agent_profit_settings.percent
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Float getPercent() {
        return percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_profit_settings.percent
     *
     * @param percent the value for agent_profit_settings.percent
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setPercent(Float percent) {
        this.percent = percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_profit_settings.floor_number
     *
     * @return the value of agent_profit_settings.floor_number
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getFloorNumber() {
        return floorNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_profit_settings.floor_number
     *
     * @param floorNumber the value for agent_profit_settings.floor_number
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setFloorNumber(Integer floorNumber) {
        this.floorNumber = floorNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_profit_settings.created_at
     *
     * @return the value of agent_profit_settings.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_profit_settings.created_at
     *
     * @param createdAt the value for agent_profit_settings.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_profit_settings.updated_at
     *
     * @return the value of agent_profit_settings.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_profit_settings.updated_at
     *
     * @param updatedAt the value for agent_profit_settings.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_profit_settings.agent_id
     *
     * @return the value of agent_profit_settings.agent_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_profit_settings.agent_id
     *
     * @param agentId the value for agent_profit_settings.agent_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setAgentId(Integer agentId) {
        this.agentId = agentId;
    }
}