package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class CsAgent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_agents.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_agents.agent_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer agentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_agents.process_user_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer processUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_agents.process_user_name
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String processUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_agents.terminals_quantity
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer terminalsQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_agents.status
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_agents.address
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_agents.reason
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_agents.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_agents.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_agents.apply_num
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String applyNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_agents.cs_agent_marks_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer csAgentMarksId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_agents.terminals_list
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String terminalsList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_agents.id
     *
     * @return the value of cs_agents.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_agents.id
     *
     * @param id the value for cs_agents.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_agents.agent_id
     *
     * @return the value of cs_agents.agent_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_agents.agent_id
     *
     * @param agentId the value for cs_agents.agent_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setAgentId(Integer agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_agents.process_user_id
     *
     * @return the value of cs_agents.process_user_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getProcessUserId() {
        return processUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_agents.process_user_id
     *
     * @param processUserId the value for cs_agents.process_user_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setProcessUserId(Integer processUserId) {
        this.processUserId = processUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_agents.process_user_name
     *
     * @return the value of cs_agents.process_user_name
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getProcessUserName() {
        return processUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_agents.process_user_name
     *
     * @param processUserName the value for cs_agents.process_user_name
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setProcessUserName(String processUserName) {
        this.processUserName = processUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_agents.terminals_quantity
     *
     * @return the value of cs_agents.terminals_quantity
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getTerminalsQuantity() {
        return terminalsQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_agents.terminals_quantity
     *
     * @param terminalsQuantity the value for cs_agents.terminals_quantity
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setTerminalsQuantity(Integer terminalsQuantity) {
        this.terminalsQuantity = terminalsQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_agents.status
     *
     * @return the value of cs_agents.status
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_agents.status
     *
     * @param status the value for cs_agents.status
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_agents.address
     *
     * @return the value of cs_agents.address
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_agents.address
     *
     * @param address the value for cs_agents.address
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_agents.reason
     *
     * @return the value of cs_agents.reason
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_agents.reason
     *
     * @param reason the value for cs_agents.reason
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_agents.created_at
     *
     * @return the value of cs_agents.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_agents.created_at
     *
     * @param createdAt the value for cs_agents.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_agents.updated_at
     *
     * @return the value of cs_agents.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_agents.updated_at
     *
     * @param updatedAt the value for cs_agents.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_agents.apply_num
     *
     * @return the value of cs_agents.apply_num
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getApplyNum() {
        return applyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_agents.apply_num
     *
     * @param applyNum the value for cs_agents.apply_num
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setApplyNum(String applyNum) {
        this.applyNum = applyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_agents.cs_agent_marks_id
     *
     * @return the value of cs_agents.cs_agent_marks_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getCsAgentMarksId() {
        return csAgentMarksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_agents.cs_agent_marks_id
     *
     * @param csAgentMarksId the value for cs_agents.cs_agent_marks_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setCsAgentMarksId(Integer csAgentMarksId) {
        this.csAgentMarksId = csAgentMarksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_agents.terminals_list
     *
     * @return the value of cs_agents.terminals_list
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getTerminalsList() {
        return terminalsList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_agents.terminals_list
     *
     * @param terminalsList the value for cs_agents.terminals_list
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setTerminalsList(String terminalsList) {
        this.terminalsList = terminalsList;
    }
}