package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class CsCancel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_cancels.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_cancels.process_user_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer processUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_cancels.process_user_name
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String processUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_cancels.terminal_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer terminalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_cancels.status
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_cancels.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_cancels.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_cancels.types
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Byte types;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_cancels.customer_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_cancels.apply_num
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String applyNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_cancels.cs_cancels_marks_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer csCancelsMarksId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_cancels.templete_info_xml
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String templeteInfoXml;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_cancels.id
     *
     * @return the value of cs_cancels.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_cancels.id
     *
     * @param id the value for cs_cancels.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_cancels.process_user_id
     *
     * @return the value of cs_cancels.process_user_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getProcessUserId() {
        return processUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_cancels.process_user_id
     *
     * @param processUserId the value for cs_cancels.process_user_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setProcessUserId(Integer processUserId) {
        this.processUserId = processUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_cancels.process_user_name
     *
     * @return the value of cs_cancels.process_user_name
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getProcessUserName() {
        return processUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_cancels.process_user_name
     *
     * @param processUserName the value for cs_cancels.process_user_name
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setProcessUserName(String processUserName) {
        this.processUserName = processUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_cancels.terminal_id
     *
     * @return the value of cs_cancels.terminal_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getTerminalId() {
        return terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_cancels.terminal_id
     *
     * @param terminalId the value for cs_cancels.terminal_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setTerminalId(Integer terminalId) {
        this.terminalId = terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_cancels.status
     *
     * @return the value of cs_cancels.status
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_cancels.status
     *
     * @param status the value for cs_cancels.status
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_cancels.created_at
     *
     * @return the value of cs_cancels.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_cancels.created_at
     *
     * @param createdAt the value for cs_cancels.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_cancels.updated_at
     *
     * @return the value of cs_cancels.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_cancels.updated_at
     *
     * @param updatedAt the value for cs_cancels.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_cancels.types
     *
     * @return the value of cs_cancels.types
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Byte getTypes() {
        return types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_cancels.types
     *
     * @param types the value for cs_cancels.types
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setTypes(Byte types) {
        this.types = types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_cancels.customer_id
     *
     * @return the value of cs_cancels.customer_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_cancels.customer_id
     *
     * @param customerId the value for cs_cancels.customer_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_cancels.apply_num
     *
     * @return the value of cs_cancels.apply_num
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getApplyNum() {
        return applyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_cancels.apply_num
     *
     * @param applyNum the value for cs_cancels.apply_num
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setApplyNum(String applyNum) {
        this.applyNum = applyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_cancels.cs_cancels_marks_id
     *
     * @return the value of cs_cancels.cs_cancels_marks_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getCsCancelsMarksId() {
        return csCancelsMarksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_cancels.cs_cancels_marks_id
     *
     * @param csCancelsMarksId the value for cs_cancels.cs_cancels_marks_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setCsCancelsMarksId(Integer csCancelsMarksId) {
        this.csCancelsMarksId = csCancelsMarksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_cancels.templete_info_xml
     *
     * @return the value of cs_cancels.templete_info_xml
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getTempleteInfoXml() {
        return templeteInfoXml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_cancels.templete_info_xml
     *
     * @param templeteInfoXml the value for cs_cancels.templete_info_xml
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setTempleteInfoXml(String templeteInfoXml) {
        this.templeteInfoXml = templeteInfoXml;
    }
}