package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class CsChange {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_changes.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_changes.process_user_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer processUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_changes.process_user_name
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String processUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_changes.terminal_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer terminalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_changes.status
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_changes.receive_address_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer receiveAddressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_changes.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_changes.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_changes.customer_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_changes.should_cencel
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Boolean shouldCencel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_changes.cs_cencel_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer csCencelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_changes.apply_num
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String applyNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_changes.cs_changel_marks_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer csChangelMarksId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_changes.return_address_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer returnAddressId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_changes.id
     *
     * @return the value of cs_changes.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_changes.id
     *
     * @param id the value for cs_changes.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_changes.process_user_id
     *
     * @return the value of cs_changes.process_user_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getProcessUserId() {
        return processUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_changes.process_user_id
     *
     * @param processUserId the value for cs_changes.process_user_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setProcessUserId(Integer processUserId) {
        this.processUserId = processUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_changes.process_user_name
     *
     * @return the value of cs_changes.process_user_name
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getProcessUserName() {
        return processUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_changes.process_user_name
     *
     * @param processUserName the value for cs_changes.process_user_name
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setProcessUserName(String processUserName) {
        this.processUserName = processUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_changes.terminal_id
     *
     * @return the value of cs_changes.terminal_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getTerminalId() {
        return terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_changes.terminal_id
     *
     * @param terminalId the value for cs_changes.terminal_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setTerminalId(Integer terminalId) {
        this.terminalId = terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_changes.status
     *
     * @return the value of cs_changes.status
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_changes.status
     *
     * @param status the value for cs_changes.status
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_changes.receive_address_id
     *
     * @return the value of cs_changes.receive_address_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getReceiveAddressId() {
        return receiveAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_changes.receive_address_id
     *
     * @param receiveAddressId the value for cs_changes.receive_address_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setReceiveAddressId(Integer receiveAddressId) {
        this.receiveAddressId = receiveAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_changes.created_at
     *
     * @return the value of cs_changes.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_changes.created_at
     *
     * @param createdAt the value for cs_changes.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_changes.updated_at
     *
     * @return the value of cs_changes.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_changes.updated_at
     *
     * @param updatedAt the value for cs_changes.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_changes.customer_id
     *
     * @return the value of cs_changes.customer_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_changes.customer_id
     *
     * @param customerId the value for cs_changes.customer_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_changes.should_cencel
     *
     * @return the value of cs_changes.should_cencel
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Boolean getShouldCencel() {
        return shouldCencel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_changes.should_cencel
     *
     * @param shouldCencel the value for cs_changes.should_cencel
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setShouldCencel(Boolean shouldCencel) {
        this.shouldCencel = shouldCencel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_changes.cs_cencel_id
     *
     * @return the value of cs_changes.cs_cencel_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getCsCencelId() {
        return csCencelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_changes.cs_cencel_id
     *
     * @param csCencelId the value for cs_changes.cs_cencel_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setCsCencelId(Integer csCencelId) {
        this.csCencelId = csCencelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_changes.apply_num
     *
     * @return the value of cs_changes.apply_num
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getApplyNum() {
        return applyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_changes.apply_num
     *
     * @param applyNum the value for cs_changes.apply_num
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setApplyNum(String applyNum) {
        this.applyNum = applyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_changes.cs_changel_marks_id
     *
     * @return the value of cs_changes.cs_changel_marks_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getCsChangelMarksId() {
        return csChangelMarksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_changes.cs_changel_marks_id
     *
     * @param csChangelMarksId the value for cs_changes.cs_changel_marks_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setCsChangelMarksId(Integer csChangelMarksId) {
        this.csChangelMarksId = csChangelMarksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_changes.return_address_id
     *
     * @return the value of cs_changes.return_address_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getReturnAddressId() {
        return returnAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_changes.return_address_id
     *
     * @param returnAddressId the value for cs_changes.return_address_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setReturnAddressId(Integer returnAddressId) {
        this.returnAddressId = returnAddressId;
    }
}