package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class CsOutStorage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_out_storages.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_out_storages.process_user_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer processUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_out_storages.process_user_name
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String processUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_out_storages.status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_out_storages.order_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_out_storages.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_out_storages.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_out_storages.apply_num
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String applyNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_out_storages.order_types
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer orderTypes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_out_storages.id
     *
     * @return the value of cs_out_storages.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_out_storages.id
     *
     * @param id the value for cs_out_storages.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_out_storages.process_user_id
     *
     * @return the value of cs_out_storages.process_user_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getProcessUserId() {
        return processUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_out_storages.process_user_id
     *
     * @param processUserId the value for cs_out_storages.process_user_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setProcessUserId(Integer processUserId) {
        this.processUserId = processUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_out_storages.process_user_name
     *
     * @return the value of cs_out_storages.process_user_name
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getProcessUserName() {
        return processUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_out_storages.process_user_name
     *
     * @param processUserName the value for cs_out_storages.process_user_name
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setProcessUserName(String processUserName) {
        this.processUserName = processUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_out_storages.status
     *
     * @return the value of cs_out_storages.status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_out_storages.status
     *
     * @param status the value for cs_out_storages.status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_out_storages.order_id
     *
     * @return the value of cs_out_storages.order_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_out_storages.order_id
     *
     * @param orderId the value for cs_out_storages.order_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_out_storages.created_at
     *
     * @return the value of cs_out_storages.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_out_storages.created_at
     *
     * @param createdAt the value for cs_out_storages.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_out_storages.updated_at
     *
     * @return the value of cs_out_storages.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_out_storages.updated_at
     *
     * @param updatedAt the value for cs_out_storages.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_out_storages.apply_num
     *
     * @return the value of cs_out_storages.apply_num
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getApplyNum() {
        return applyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_out_storages.apply_num
     *
     * @param applyNum the value for cs_out_storages.apply_num
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setApplyNum(String applyNum) {
        this.applyNum = applyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_out_storages.order_types
     *
     * @return the value of cs_out_storages.order_types
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getOrderTypes() {
        return orderTypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_out_storages.order_types
     *
     * @param orderTypes the value for cs_out_storages.order_types
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setOrderTypes(Integer orderTypes) {
        this.orderTypes = orderTypes;
    }
}