package com.comdosoft.financial.manage.domain.zhangfu;

public class CustomerIntentionWithBLOBs extends CustomerIntention {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_intentions.content
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_intentions.mark_xml
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String markXml;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_intentions.content
     *
     * @return the value of customer_intentions.content
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_intentions.content
     *
     * @param content the value for customer_intentions.content
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_intentions.mark_xml
     *
     * @return the value of customer_intentions.mark_xml
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getMarkXml() {
        return markXml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_intentions.mark_xml
     *
     * @param markXml the value for customer_intentions.mark_xml
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setMarkXml(String markXml) {
        this.markXml = markXml;
    }
}