package com.comdosoft.financial.manage.domain.zhangfu;

public class CustomerAgentRelationMark {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_agent_relation_marks.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_agent_relation_marks.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_agent_relation_marks.customer_agent_relation_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer customerAgentRelationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_agent_relation_marks.customer_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_agent_relation_marks.content
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_agent_relation_marks.id
     *
     * @return the value of customer_agent_relation_marks.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_agent_relation_marks.id
     *
     * @param id the value for customer_agent_relation_marks.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_agent_relation_marks.created_at
     *
     * @return the value of customer_agent_relation_marks.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_agent_relation_marks.created_at
     *
     * @param createdAt the value for customer_agent_relation_marks.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setCreatedAt(Integer createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_agent_relation_marks.customer_agent_relation_id
     *
     * @return the value of customer_agent_relation_marks.customer_agent_relation_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getCustomerAgentRelationId() {
        return customerAgentRelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_agent_relation_marks.customer_agent_relation_id
     *
     * @param customerAgentRelationId the value for customer_agent_relation_marks.customer_agent_relation_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setCustomerAgentRelationId(Integer customerAgentRelationId) {
        this.customerAgentRelationId = customerAgentRelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_agent_relation_marks.customer_id
     *
     * @return the value of customer_agent_relation_marks.customer_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_agent_relation_marks.customer_id
     *
     * @param customerId the value for customer_agent_relation_marks.customer_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_agent_relation_marks.content
     *
     * @return the value of customer_agent_relation_marks.content
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_agent_relation_marks.content
     *
     * @param content the value for customer_agent_relation_marks.content
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }
}