package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class CustomerAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_addresses.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_addresses.city_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_addresses.receiver
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_addresses.address
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_addresses.moblephone
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String moblephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_addresses.zip_code
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_addresses.is_default
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Boolean isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_addresses.customer_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_addresses.status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_addresses.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_addresses.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_addresses.telphone
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String telphone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_addresses.id
     *
     * @return the value of customer_addresses.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_addresses.id
     *
     * @param id the value for customer_addresses.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_addresses.city_id
     *
     * @return the value of customer_addresses.city_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_addresses.city_id
     *
     * @param cityId the value for customer_addresses.city_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_addresses.receiver
     *
     * @return the value of customer_addresses.receiver
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_addresses.receiver
     *
     * @param receiver the value for customer_addresses.receiver
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_addresses.address
     *
     * @return the value of customer_addresses.address
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_addresses.address
     *
     * @param address the value for customer_addresses.address
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_addresses.moblephone
     *
     * @return the value of customer_addresses.moblephone
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getMoblephone() {
        return moblephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_addresses.moblephone
     *
     * @param moblephone the value for customer_addresses.moblephone
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setMoblephone(String moblephone) {
        this.moblephone = moblephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_addresses.zip_code
     *
     * @return the value of customer_addresses.zip_code
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_addresses.zip_code
     *
     * @param zipCode the value for customer_addresses.zip_code
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_addresses.is_default
     *
     * @return the value of customer_addresses.is_default
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_addresses.is_default
     *
     * @param isDefault the value for customer_addresses.is_default
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_addresses.customer_id
     *
     * @return the value of customer_addresses.customer_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_addresses.customer_id
     *
     * @param customerId the value for customer_addresses.customer_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_addresses.status
     *
     * @return the value of customer_addresses.status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_addresses.status
     *
     * @param status the value for customer_addresses.status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_addresses.created_at
     *
     * @return the value of customer_addresses.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_addresses.created_at
     *
     * @param createdAt the value for customer_addresses.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_addresses.updated_at
     *
     * @return the value of customer_addresses.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_addresses.updated_at
     *
     * @param updatedAt the value for customer_addresses.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_addresses.telphone
     *
     * @return the value of customer_addresses.telphone
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_addresses.telphone
     *
     * @param telphone the value for customer_addresses.telphone
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }
}