package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class CustomerIntegralConvert {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_integral_converts.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_integral_converts.quantity
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_integral_converts.bank_name
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_integral_converts.bank_account
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String bankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_integral_converts.price
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_integral_converts.status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_integral_converts.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_integral_converts.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_integral_converts.customer_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_integral_converts.process_user_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer processUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_integral_converts.process_user_name
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String processUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_integral_converts.mark_xml
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String markXml;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_integral_converts.id
     *
     * @return the value of customer_integral_converts.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_integral_converts.id
     *
     * @param id the value for customer_integral_converts.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_integral_converts.quantity
     *
     * @return the value of customer_integral_converts.quantity
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_integral_converts.quantity
     *
     * @param quantity the value for customer_integral_converts.quantity
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_integral_converts.bank_name
     *
     * @return the value of customer_integral_converts.bank_name
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_integral_converts.bank_name
     *
     * @param bankName the value for customer_integral_converts.bank_name
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_integral_converts.bank_account
     *
     * @return the value of customer_integral_converts.bank_account
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_integral_converts.bank_account
     *
     * @param bankAccount the value for customer_integral_converts.bank_account
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_integral_converts.price
     *
     * @return the value of customer_integral_converts.price
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_integral_converts.price
     *
     * @param price the value for customer_integral_converts.price
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_integral_converts.status
     *
     * @return the value of customer_integral_converts.status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_integral_converts.status
     *
     * @param status the value for customer_integral_converts.status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_integral_converts.created_at
     *
     * @return the value of customer_integral_converts.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_integral_converts.created_at
     *
     * @param createdAt the value for customer_integral_converts.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_integral_converts.updated_at
     *
     * @return the value of customer_integral_converts.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_integral_converts.updated_at
     *
     * @param updatedAt the value for customer_integral_converts.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_integral_converts.customer_id
     *
     * @return the value of customer_integral_converts.customer_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_integral_converts.customer_id
     *
     * @param customerId the value for customer_integral_converts.customer_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_integral_converts.process_user_id
     *
     * @return the value of customer_integral_converts.process_user_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getProcessUserId() {
        return processUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_integral_converts.process_user_id
     *
     * @param processUserId the value for customer_integral_converts.process_user_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setProcessUserId(Integer processUserId) {
        this.processUserId = processUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_integral_converts.process_user_name
     *
     * @return the value of customer_integral_converts.process_user_name
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getProcessUserName() {
        return processUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_integral_converts.process_user_name
     *
     * @param processUserName the value for customer_integral_converts.process_user_name
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setProcessUserName(String processUserName) {
        this.processUserName = processUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_integral_converts.mark_xml
     *
     * @return the value of customer_integral_converts.mark_xml
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getMarkXml() {
        return markXml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_integral_converts.mark_xml
     *
     * @param markXml the value for customer_integral_converts.mark_xml
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setMarkXml(String markXml) {
        this.markXml = markXml;
    }
}