package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.username
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.password
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.account_type
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Boolean accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.name
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.city_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.types
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Byte types;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.last_logined_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Date lastLoginedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.integral
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer integral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.device_code
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String deviceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.phone
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.email
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.id
     *
     * @return the value of customers.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.id
     *
     * @param id the value for customers.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.username
     *
     * @return the value of customers.username
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.username
     *
     * @param username the value for customers.username
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.password
     *
     * @return the value of customers.password
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.password
     *
     * @param password the value for customers.password
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.account_type
     *
     * @return the value of customers.account_type
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Boolean getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.account_type
     *
     * @param accountType the value for customers.account_type
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setAccountType(Boolean accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.name
     *
     * @return the value of customers.name
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.name
     *
     * @param name the value for customers.name
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.city_id
     *
     * @return the value of customers.city_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.city_id
     *
     * @param cityId the value for customers.city_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.types
     *
     * @return the value of customers.types
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Byte getTypes() {
        return types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.types
     *
     * @param types the value for customers.types
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setTypes(Byte types) {
        this.types = types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.last_logined_at
     *
     * @return the value of customers.last_logined_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Date getLastLoginedAt() {
        return lastLoginedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.last_logined_at
     *
     * @param lastLoginedAt the value for customers.last_logined_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setLastLoginedAt(Date lastLoginedAt) {
        this.lastLoginedAt = lastLoginedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.integral
     *
     * @return the value of customers.integral
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.integral
     *
     * @param integral the value for customers.integral
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.status
     *
     * @return the value of customers.status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.status
     *
     * @param status the value for customers.status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.device_code
     *
     * @return the value of customers.device_code
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getDeviceCode() {
        return deviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.device_code
     *
     * @param deviceCode the value for customers.device_code
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setDeviceCode(String deviceCode) {
        this.deviceCode = deviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.created_at
     *
     * @return the value of customers.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.created_at
     *
     * @param createdAt the value for customers.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.updated_at
     *
     * @return the value of customers.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.updated_at
     *
     * @param updatedAt the value for customers.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.phone
     *
     * @return the value of customers.phone
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.phone
     *
     * @param phone the value for customers.phone
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.email
     *
     * @return the value of customers.email
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.email
     *
     * @param email the value for customers.email
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }
}