package com.comdosoft.financial.manage.domain.zhangfu;

public class CustomerAgentRelationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_agent_relations.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_agent_relations.customer_agent_relation_marks_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer customerAgentRelationMarksId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_agent_relations.id
     *
     * @return the value of customer_agent_relations.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_agent_relations.id
     *
     * @param id the value for customer_agent_relations.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_agent_relations.customer_agent_relation_marks_id
     *
     * @return the value of customer_agent_relations.customer_agent_relation_marks_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getCustomerAgentRelationMarksId() {
        return customerAgentRelationMarksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_agent_relations.customer_agent_relation_marks_id
     *
     * @param customerAgentRelationMarksId the value for customer_agent_relations.customer_agent_relation_marks_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setCustomerAgentRelationMarksId(Integer customerAgentRelationMarksId) {
        this.customerAgentRelationMarksId = customerAgentRelationMarksId;
    }
}