package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class DictionaryCreditType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_credit_types.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_credit_types.name
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_credit_types.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_credit_types.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_credit_types.description
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_credit_types.id
     *
     * @return the value of dictionary_credit_types.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_credit_types.id
     *
     * @param id the value for dictionary_credit_types.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_credit_types.name
     *
     * @return the value of dictionary_credit_types.name
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_credit_types.name
     *
     * @param name the value for dictionary_credit_types.name
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_credit_types.created_at
     *
     * @return the value of dictionary_credit_types.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_credit_types.created_at
     *
     * @param createdAt the value for dictionary_credit_types.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_credit_types.updated_at
     *
     * @return the value of dictionary_credit_types.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_credit_types.updated_at
     *
     * @param updatedAt the value for dictionary_credit_types.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_credit_types.description
     *
     * @return the value of dictionary_credit_types.description
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_credit_types.description
     *
     * @param description the value for dictionary_credit_types.description
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }
}