package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class DictionaryTradeStandardRate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_trade_standard_rates.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_trade_standard_rates.merchant_type_name
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String merchantTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_trade_standard_rates.base_rate
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String baseRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_trade_standard_rates.description
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_trade_standard_rates.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_trade_standard_rates.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_trade_standard_rates.id
     *
     * @return the value of dictionary_trade_standard_rates.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_trade_standard_rates.id
     *
     * @param id the value for dictionary_trade_standard_rates.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_trade_standard_rates.merchant_type_name
     *
     * @return the value of dictionary_trade_standard_rates.merchant_type_name
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getMerchantTypeName() {
        return merchantTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_trade_standard_rates.merchant_type_name
     *
     * @param merchantTypeName the value for dictionary_trade_standard_rates.merchant_type_name
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setMerchantTypeName(String merchantTypeName) {
        this.merchantTypeName = merchantTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_trade_standard_rates.base_rate
     *
     * @return the value of dictionary_trade_standard_rates.base_rate
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getBaseRate() {
        return baseRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_trade_standard_rates.base_rate
     *
     * @param baseRate the value for dictionary_trade_standard_rates.base_rate
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setBaseRate(String baseRate) {
        this.baseRate = baseRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_trade_standard_rates.description
     *
     * @return the value of dictionary_trade_standard_rates.description
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_trade_standard_rates.description
     *
     * @param description the value for dictionary_trade_standard_rates.description
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_trade_standard_rates.created_at
     *
     * @return the value of dictionary_trade_standard_rates.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_trade_standard_rates.created_at
     *
     * @param createdAt the value for dictionary_trade_standard_rates.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_trade_standard_rates.updated_at
     *
     * @return the value of dictionary_trade_standard_rates.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_trade_standard_rates.updated_at
     *
     * @param updatedAt the value for dictionary_trade_standard_rates.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}