package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class DictionaryTradeType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_trade_types.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_trade_types.trade_type
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Byte tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_trade_types.trade_value
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String tradeValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_trade_types.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary_trade_types.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_trade_types.id
     *
     * @return the value of dictionary_trade_types.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_trade_types.id
     *
     * @param id the value for dictionary_trade_types.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_trade_types.trade_type
     *
     * @return the value of dictionary_trade_types.trade_type
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Byte getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_trade_types.trade_type
     *
     * @param tradeType the value for dictionary_trade_types.trade_type
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setTradeType(Byte tradeType) {
        this.tradeType = tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_trade_types.trade_value
     *
     * @return the value of dictionary_trade_types.trade_value
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getTradeValue() {
        return tradeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_trade_types.trade_value
     *
     * @param tradeValue the value for dictionary_trade_types.trade_value
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setTradeValue(String tradeValue) {
        this.tradeValue = tradeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_trade_types.created_at
     *
     * @return the value of dictionary_trade_types.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_trade_types.created_at
     *
     * @param createdAt the value for dictionary_trade_types.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary_trade_types.updated_at
     *
     * @return the value of dictionary_trade_types.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary_trade_types.updated_at
     *
     * @param updatedAt the value for dictionary_trade_types.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}