package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class exchangeGoodsRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_goods_records.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_goods_records.agent_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer agentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_goods_records.from_agent_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer fromAgentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_goods_records.to_agent_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer toAgentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_goods_records.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_goods_records.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_goods_records.terminals_list
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String terminalsList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_goods_records.id
     *
     * @return the value of exchange_goods_records.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_goods_records.id
     *
     * @param id the value for exchange_goods_records.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_goods_records.agent_id
     *
     * @return the value of exchange_goods_records.agent_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_goods_records.agent_id
     *
     * @param agentId the value for exchange_goods_records.agent_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setAgentId(Integer agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_goods_records.from_agent_id
     *
     * @return the value of exchange_goods_records.from_agent_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getFromAgentId() {
        return fromAgentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_goods_records.from_agent_id
     *
     * @param fromAgentId the value for exchange_goods_records.from_agent_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setFromAgentId(Integer fromAgentId) {
        this.fromAgentId = fromAgentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_goods_records.to_agent_id
     *
     * @return the value of exchange_goods_records.to_agent_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getToAgentId() {
        return toAgentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_goods_records.to_agent_id
     *
     * @param toAgentId the value for exchange_goods_records.to_agent_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setToAgentId(Integer toAgentId) {
        this.toAgentId = toAgentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_goods_records.created_at
     *
     * @return the value of exchange_goods_records.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_goods_records.created_at
     *
     * @param createdAt the value for exchange_goods_records.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_goods_records.updated_at
     *
     * @return the value of exchange_goods_records.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_goods_records.updated_at
     *
     * @param updatedAt the value for exchange_goods_records.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_goods_records.terminals_list
     *
     * @return the value of exchange_goods_records.terminals_list
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getTerminalsList() {
        return terminalsList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_goods_records.terminals_list
     *
     * @param terminalsList the value for exchange_goods_records.terminals_list
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setTerminalsList(String terminalsList) {
        this.terminalsList = terminalsList;
    }
}