package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class Factory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factories.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factories.name
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factories.logo_file_path
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String logoFilePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factories.website_url
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String websiteUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factories.types
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Byte types;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factories.status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factories.business_license_no
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String businessLicenseNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factories.tax_registered_no
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String taxRegisteredNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factories.product_certification_path
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String productCertificationPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factories.business_license_path
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String businessLicensePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factories.tax_registered_path
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String taxRegisteredPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factories.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factories.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factories.customer_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factories.description
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factories.id
     *
     * @return the value of factories.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factories.id
     *
     * @param id the value for factories.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factories.name
     *
     * @return the value of factories.name
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factories.name
     *
     * @param name the value for factories.name
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factories.logo_file_path
     *
     * @return the value of factories.logo_file_path
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getLogoFilePath() {
        return logoFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factories.logo_file_path
     *
     * @param logoFilePath the value for factories.logo_file_path
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setLogoFilePath(String logoFilePath) {
        this.logoFilePath = logoFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factories.website_url
     *
     * @return the value of factories.website_url
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getWebsiteUrl() {
        return websiteUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factories.website_url
     *
     * @param websiteUrl the value for factories.website_url
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setWebsiteUrl(String websiteUrl) {
        this.websiteUrl = websiteUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factories.types
     *
     * @return the value of factories.types
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Byte getTypes() {
        return types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factories.types
     *
     * @param types the value for factories.types
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setTypes(Byte types) {
        this.types = types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factories.status
     *
     * @return the value of factories.status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factories.status
     *
     * @param status the value for factories.status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factories.business_license_no
     *
     * @return the value of factories.business_license_no
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getBusinessLicenseNo() {
        return businessLicenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factories.business_license_no
     *
     * @param businessLicenseNo the value for factories.business_license_no
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setBusinessLicenseNo(String businessLicenseNo) {
        this.businessLicenseNo = businessLicenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factories.tax_registered_no
     *
     * @return the value of factories.tax_registered_no
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getTaxRegisteredNo() {
        return taxRegisteredNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factories.tax_registered_no
     *
     * @param taxRegisteredNo the value for factories.tax_registered_no
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setTaxRegisteredNo(String taxRegisteredNo) {
        this.taxRegisteredNo = taxRegisteredNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factories.product_certification_path
     *
     * @return the value of factories.product_certification_path
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getProductCertificationPath() {
        return productCertificationPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factories.product_certification_path
     *
     * @param productCertificationPath the value for factories.product_certification_path
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setProductCertificationPath(String productCertificationPath) {
        this.productCertificationPath = productCertificationPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factories.business_license_path
     *
     * @return the value of factories.business_license_path
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getBusinessLicensePath() {
        return businessLicensePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factories.business_license_path
     *
     * @param businessLicensePath the value for factories.business_license_path
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setBusinessLicensePath(String businessLicensePath) {
        this.businessLicensePath = businessLicensePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factories.tax_registered_path
     *
     * @return the value of factories.tax_registered_path
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getTaxRegisteredPath() {
        return taxRegisteredPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factories.tax_registered_path
     *
     * @param taxRegisteredPath the value for factories.tax_registered_path
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setTaxRegisteredPath(String taxRegisteredPath) {
        this.taxRegisteredPath = taxRegisteredPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factories.created_at
     *
     * @return the value of factories.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factories.created_at
     *
     * @param createdAt the value for factories.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factories.updated_at
     *
     * @return the value of factories.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factories.updated_at
     *
     * @param updatedAt the value for factories.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factories.customer_id
     *
     * @return the value of factories.customer_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factories.customer_id
     *
     * @param customerId the value for factories.customer_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factories.description
     *
     * @return the value of factories.description
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factories.description
     *
     * @param description the value for factories.description
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }
}