package com.comdosoft.financial.manage.domain.zhangfu;

public class GoodKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.good_marks_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer goodMarksId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.good_marks_id
     *
     * @return the value of goods.good_marks_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getGoodMarksId() {
        return goodMarksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.good_marks_id
     *
     * @param goodMarksId the value for goods.good_marks_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setGoodMarksId(Integer goodMarksId) {
        this.goodMarksId = goodMarksId;
    }
}