package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class GoodsPicture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pictures.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pictures.url_path
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String urlPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pictures.good_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer goodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pictures.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pictures.id
     *
     * @return the value of goods_pictures.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pictures.id
     *
     * @param id the value for goods_pictures.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pictures.url_path
     *
     * @return the value of goods_pictures.url_path
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getUrlPath() {
        return urlPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pictures.url_path
     *
     * @param urlPath the value for goods_pictures.url_path
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setUrlPath(String urlPath) {
        this.urlPath = urlPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pictures.good_id
     *
     * @return the value of goods_pictures.good_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pictures.good_id
     *
     * @param goodId the value for goods_pictures.good_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setGoodId(Integer goodId) {
        this.goodId = goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pictures.created_at
     *
     * @return the value of goods_pictures.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pictures.created_at
     *
     * @param createdAt the value for goods_pictures.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}