package com.comdosoft.financial.manage.domain.zhangfu;

public class Message_receiver {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_receivers.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_receivers.customer_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_receivers.sys_message_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer sysMessageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_receivers.status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_receivers.id
     *
     * @return the value of message_receivers.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_receivers.id
     *
     * @param id the value for message_receivers.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_receivers.customer_id
     *
     * @return the value of message_receivers.customer_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_receivers.customer_id
     *
     * @param customerId the value for message_receivers.customer_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_receivers.sys_message_id
     *
     * @return the value of message_receivers.sys_message_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getSysMessageId() {
        return sysMessageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_receivers.sys_message_id
     *
     * @param sysMessageId the value for message_receivers.sys_message_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setSysMessageId(Integer sysMessageId) {
        this.sysMessageId = sysMessageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_receivers.status
     *
     * @return the value of message_receivers.status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_receivers.status
     *
     * @param status the value for message_receivers.status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}