package com.comdosoft.financial.manage.domain.zhangfu;

public class OpeningVideoVerify {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opening_video_verifies.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opening_video_verifies.status
	 * @mbggenerated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opening_video_verifies.opening_requirement_id
	 * @mbggenerated
	 */
	private Integer openingRequirementId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opening_video_verifies.opening_apply_id
	 * @mbggenerated
	 */
	private Integer openingApplyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opening_video_verifies.video_url
	 * @mbggenerated
	 */
	private String videoUrl;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opening_video_verifies.id
	 * @return  the value of opening_video_verifies.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opening_video_verifies.id
	 * @param id  the value for opening_video_verifies.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opening_video_verifies.status
	 * @return  the value of opening_video_verifies.status
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opening_video_verifies.status
	 * @param status  the value for opening_video_verifies.status
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opening_video_verifies.opening_requirement_id
	 * @return  the value of opening_video_verifies.opening_requirement_id
	 * @mbggenerated
	 */
	public Integer getOpeningRequirementId() {
		return openingRequirementId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opening_video_verifies.opening_requirement_id
	 * @param openingRequirementId  the value for opening_video_verifies.opening_requirement_id
	 * @mbggenerated
	 */
	public void setOpeningRequirementId(Integer openingRequirementId) {
		this.openingRequirementId = openingRequirementId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opening_video_verifies.opening_apply_id
	 * @return  the value of opening_video_verifies.opening_apply_id
	 * @mbggenerated
	 */
	public Integer getOpeningApplyId() {
		return openingApplyId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opening_video_verifies.opening_apply_id
	 * @param openingApplyId  the value for opening_video_verifies.opening_apply_id
	 * @mbggenerated
	 */
	public void setOpeningApplyId(Integer openingApplyId) {
		this.openingApplyId = openingApplyId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opening_video_verifies.video_url
	 * @return  the value of opening_video_verifies.video_url
	 * @mbggenerated
	 */
	public String getVideoUrl() {
		return videoUrl;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opening_video_verifies.video_url
	 * @param videoUrl  the value for opening_video_verifies.video_url
	 * @mbggenerated
	 */
	public void setVideoUrl(String videoUrl) {
		this.videoUrl = videoUrl;
	}
	public final static Integer STATUS_TRUE = 1;
    public final static Integer STATUS_FALSE = 0;


}