package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class OperateRecord {
	/**
	 * 代理商代购操作
	 */
	public static final Integer TYPES_AGENT_PROXY = 1; //代理商代购操作
	/**
	 * 代理商批购操作
	 */
	public static final Integer TYPES_AGENT_BATCH = 2; //代理商批购操作
	/**
	 * 用户订单操作
	 */
	public static final Integer TYPES_USER_ORDER = 3; //用户订单操作
	/**
	 * 购买意向操作
	 */
	public static final Integer TYPES_BUY_INTENTION = 4 ;//购买意向操作
	/**
	 * 交易流水操作
	 */
	public static final Integer TYPES_TRANSACTION_FLOWING =5;  //交易流水操作
	/**
	 * 出库操作
	 */
	public static final Integer TYPES_CHECKOUT = 6; //出库操作
	/**
	 * 积分兑换操作
	 */
	public static final Integer TYPES_POINTS_EXCHANGE = 7;//积分兑换操作
	/**
	 * 认证开通操作
	 */
	public static final Integer TYPES_OPEN_AUTHENTICATION =8; //认证开通操作
	/**
	 * 售后库存管理操作
	 */
	public static final Integer TYPES_AFTERMARKET_INVENTORY = 9;//9	售后库存管理操作
	/**
	 * 退款操作
	 */
	public static final Integer TYPES_REFUND = 10;//	10	退款操作
	/**
	 * 商品管理操作
	 */
	public static final Integer TYPES_MERCHANDISE = 11;//	11	商品管理操作
	/**
	 * 支付通道管理操作
	 */
	public static final Integer TYPES_PAYMENT_CHANNELS = 12;//	12	支付通道管理操作
	/**
	 * 代理商售后操作
	 */
	public static final Integer TYPES_AGENT_AFTERMARKET = 13;//	13	代理商售后操作
	/**
	 * 更新资料售后操作
	 */
	public static final Integer TYPES_UPDATE_AFTERMARKET = 14;//	14	更新资料售后操作
	/**
	 * 换货操作
	 */
	public static final Integer TYPES_CHANGE = 15;//	15	换货操作
	/**
	 * 退货操作
	 */
	public static final Integer TYPES_RETRUN = 16;//	16	退货操作
	/**
	 * 	维修操作
	 */
	public static final Integer TYPES_REPAIR = 17;//	17	维修操作
	/**
	 * 注销操作
	 */
	public static final Integer TYPES_CANCEL = 18;//	18	注销操作
	/**
	 * 租赁退换操作
	 */
	public static final Integer TYPES_LEASE = 19;//	19	租赁退换操作
	/**
	 * 系统-代理商操作
	 */
	public static final Integer TYPES_SYSTEM_AGENT = 20;//	20	系统-代理商操作
	/**
	 * 系统-第三方机构操作
	 */
	public static final Integer TYPES_SYSTEM_THIRD_PARTY = 21;//	21	系统-第三方机构操作
	/**
	 * 系统-数据字典操作
	 */
	public static final Integer TYPES_SYSTEM_DATA_DICTIONARY = 22;//	22	系统-数据字典操作
	/**
	 * 系统-网站内容操作
	 */
	public static final Integer TYPES_SYSTEM_WEB = 23;//	23	系统-网站内容操作
	/**
	 * 系统-系统参数
	 */
	public static final Integer TYPES_SYSTEM_SETTING = 24;//	24	系统-系统参数
	/**
	 * 系统-消息操作
	 */
	public static final Integer TYPES_SYSTEM_MESSAGE = 25;//	25	系统-消息操作
	/**
	 * 系统-管理角色操作
	 */
	public static final Integer TYPES_SYSTEM_MANAGERIAL_ROLES= 26;//	26	系统-管理角色操作
	/**
	 * 	系统-管理账号操作
	 */
	public static final Integer TYPES_SYSTEM_MANAGERIAL_ACCOUNT= 27;//	27	系统-管理账号操作
	/**
	 * 系统-账号设置操作
	 */
	public static final Integer TYPES_SYSTEM_ACCOUNT_SETTING = 28;//	28	系统-账号设置操作
	/**
	 * 用户操作
	 */
	public static final Integer TYPES_USER = 29;//	29	用户操作
	/**
	 * 终端操作
	 */
	public static final Integer TYPES_TERMINAL = 30;//	30	终端操作
	/**
	 * 接口-申请开通操作
	 */
	public static final Integer TYPES_INTERFACE_TO_APPLY_FOR = 31;//	31	接口-申请开通操作
	/**
	 * 接口-交易流水操作
	 */
	public static final Integer TYPES_INTERFACE_TRANSACTION_FLOWING = 32;//	32	接口-交易流水操作
	/**
	 * 接口-其他操作
	 */
	public static final Integer TYPES_INTERFACE_OTHER = 33;//	33	接口-其他操作
	
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operate_records.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operate_records.operate_user_id
	 * @mbggenerated
	 */
	private Integer operateUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operate_records.operate_user_type
	 * @mbggenerated
	 */
	private Byte operateUserType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operate_records.types
	 * @mbggenerated
	 */
	private Integer types;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operate_records.created_at
	 * @mbggenerated
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operate_records.updated_at
	 * @mbggenerated
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operate_records.operate_target_id
	 * @mbggenerated
	 */
	private Integer operateTargetId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operate_records.operate_target_type
	 * @mbggenerated
	 */
	private Byte operateTargetType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operate_records.operate_user_name
	 * @mbggenerated
	 */
	private String operateUserName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operate_records.content
	 * @mbggenerated
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operate_records.id
	 * @return  the value of operate_records.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operate_records.id
	 * @param id  the value for operate_records.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operate_records.operate_user_id
	 * @return  the value of operate_records.operate_user_id
	 * @mbggenerated
	 */
	public Integer getOperateUserId() {
		return operateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operate_records.operate_user_id
	 * @param operateUserId  the value for operate_records.operate_user_id
	 * @mbggenerated
	 */
	public void setOperateUserId(Integer operateUserId) {
		this.operateUserId = operateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operate_records.operate_user_type
	 * @return  the value of operate_records.operate_user_type
	 * @mbggenerated
	 */
	public Byte getOperateUserType() {
		return operateUserType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operate_records.operate_user_type
	 * @param operateUserType  the value for operate_records.operate_user_type
	 * @mbggenerated
	 */
	public void setOperateUserType(Byte operateUserType) {
		this.operateUserType = operateUserType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operate_records.types
	 * @return  the value of operate_records.types
	 * @mbggenerated
	 */
	public Integer getTypes() {
		return types;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operate_records.types
	 * @param types  the value for operate_records.types
	 * @mbggenerated
	 */
	public void setTypes(Integer types) {
		this.types = types;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operate_records.created_at
	 * @return  the value of operate_records.created_at
	 * @mbggenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operate_records.created_at
	 * @param createdAt  the value for operate_records.created_at
	 * @mbggenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operate_records.updated_at
	 * @return  the value of operate_records.updated_at
	 * @mbggenerated
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operate_records.updated_at
	 * @param updatedAt  the value for operate_records.updated_at
	 * @mbggenerated
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operate_records.operate_target_id
	 * @return  the value of operate_records.operate_target_id
	 * @mbggenerated
	 */
	public Integer getOperateTargetId() {
		return operateTargetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operate_records.operate_target_id
	 * @param operateTargetId  the value for operate_records.operate_target_id
	 * @mbggenerated
	 */
	public void setOperateTargetId(Integer operateTargetId) {
		this.operateTargetId = operateTargetId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operate_records.operate_target_type
	 * @return  the value of operate_records.operate_target_type
	 * @mbggenerated
	 */
	public Byte getOperateTargetType() {
		return operateTargetType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operate_records.operate_target_type
	 * @param operateTargetType  the value for operate_records.operate_target_type
	 * @mbggenerated
	 */
	public void setOperateTargetType(Byte operateTargetType) {
		this.operateTargetType = operateTargetType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operate_records.operate_user_name
	 * @return  the value of operate_records.operate_user_name
	 * @mbggenerated
	 */
	public String getOperateUserName() {
		return operateUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operate_records.operate_user_name
	 * @param operateUserName  the value for operate_records.operate_user_name
	 * @mbggenerated
	 */
	public void setOperateUserName(String operateUserName) {
		this.operateUserName = operateUserName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operate_records.content
	 * @return  the value of operate_records.content
	 * @mbggenerated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operate_records.content
	 * @param content  the value for operate_records.content
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content;
	}
}