package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class OrderTradeRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade_records.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade_records.trade_number
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String tradeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade_records.batch_number
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String batchNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade_records.merchant_number
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer merchantNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade_records.amount
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade_records.poundage
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer poundage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade_records.traded_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Date tradedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade_records.order_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade_records.account_number
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String accountNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade_records.account_name
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade_records.actual_payment_price
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer actualPaymentPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade_records.paid_result
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Byte paidResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade_records.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade_records.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade_records.traded_status
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer tradedStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_trade_records.pay_types
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer payTypes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade_records.id
     *
     * @return the value of order_trade_records.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade_records.id
     *
     * @param id the value for order_trade_records.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade_records.trade_number
     *
     * @return the value of order_trade_records.trade_number
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getTradeNumber() {
        return tradeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade_records.trade_number
     *
     * @param tradeNumber the value for order_trade_records.trade_number
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setTradeNumber(String tradeNumber) {
        this.tradeNumber = tradeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade_records.batch_number
     *
     * @return the value of order_trade_records.batch_number
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getBatchNumber() {
        return batchNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade_records.batch_number
     *
     * @param batchNumber the value for order_trade_records.batch_number
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setBatchNumber(String batchNumber) {
        this.batchNumber = batchNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade_records.merchant_number
     *
     * @return the value of order_trade_records.merchant_number
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getMerchantNumber() {
        return merchantNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade_records.merchant_number
     *
     * @param merchantNumber the value for order_trade_records.merchant_number
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setMerchantNumber(Integer merchantNumber) {
        this.merchantNumber = merchantNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade_records.amount
     *
     * @return the value of order_trade_records.amount
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade_records.amount
     *
     * @param amount the value for order_trade_records.amount
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade_records.poundage
     *
     * @return the value of order_trade_records.poundage
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getPoundage() {
        return poundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade_records.poundage
     *
     * @param poundage the value for order_trade_records.poundage
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setPoundage(Integer poundage) {
        this.poundage = poundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade_records.traded_at
     *
     * @return the value of order_trade_records.traded_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Date getTradedAt() {
        return tradedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade_records.traded_at
     *
     * @param tradedAt the value for order_trade_records.traded_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setTradedAt(Date tradedAt) {
        this.tradedAt = tradedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade_records.order_id
     *
     * @return the value of order_trade_records.order_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade_records.order_id
     *
     * @param orderId the value for order_trade_records.order_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade_records.account_number
     *
     * @return the value of order_trade_records.account_number
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade_records.account_number
     *
     * @param accountNumber the value for order_trade_records.account_number
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade_records.account_name
     *
     * @return the value of order_trade_records.account_name
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade_records.account_name
     *
     * @param accountName the value for order_trade_records.account_name
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade_records.actual_payment_price
     *
     * @return the value of order_trade_records.actual_payment_price
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getActualPaymentPrice() {
        return actualPaymentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade_records.actual_payment_price
     *
     * @param actualPaymentPrice the value for order_trade_records.actual_payment_price
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setActualPaymentPrice(Integer actualPaymentPrice) {
        this.actualPaymentPrice = actualPaymentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade_records.paid_result
     *
     * @return the value of order_trade_records.paid_result
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Byte getPaidResult() {
        return paidResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade_records.paid_result
     *
     * @param paidResult the value for order_trade_records.paid_result
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setPaidResult(Byte paidResult) {
        this.paidResult = paidResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade_records.created_at
     *
     * @return the value of order_trade_records.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade_records.created_at
     *
     * @param createdAt the value for order_trade_records.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade_records.updated_at
     *
     * @return the value of order_trade_records.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade_records.updated_at
     *
     * @param updatedAt the value for order_trade_records.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade_records.traded_status
     *
     * @return the value of order_trade_records.traded_status
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getTradedStatus() {
        return tradedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade_records.traded_status
     *
     * @param tradedStatus the value for order_trade_records.traded_status
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setTradedStatus(Integer tradedStatus) {
        this.tradedStatus = tradedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_trade_records.pay_types
     *
     * @return the value of order_trade_records.pay_types
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getPayTypes() {
        return payTypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_trade_records.pay_types
     *
     * @param payTypes the value for order_trade_records.pay_types
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setPayTypes(Integer payTypes) {
        this.payTypes = payTypes;
    }
}