package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_number
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customer_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.total_price
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.payed_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Date payedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.types
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Byte types;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customer_address_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer customerAddressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.need_invoice
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Boolean needInvoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.actual_price
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer actualPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.front_money
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer frontMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.front_pay_status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Byte frontPayStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pay_status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Byte payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.created_user_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer createdUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.created_user_type
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Byte createdUserType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.process_user_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer processUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.process_user_name
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String processUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.agent_order_marks_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer agentOrderMarksId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.belongs_to
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer belongsTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.invoice_type
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer invoiceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.comment
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.invoice_info
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String invoiceInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_number
     *
     * @return the value of orders.order_number
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_number
     *
     * @param orderNumber the value for orders.order_number
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customer_id
     *
     * @return the value of orders.customer_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customer_id
     *
     * @param customerId the value for orders.customer_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.total_price
     *
     * @return the value of orders.total_price
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.total_price
     *
     * @param totalPrice the value for orders.total_price
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setTotalPrice(Integer totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.status
     *
     * @return the value of orders.status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.status
     *
     * @param status the value for orders.status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.payed_at
     *
     * @return the value of orders.payed_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Date getPayedAt() {
        return payedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.payed_at
     *
     * @param payedAt the value for orders.payed_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setPayedAt(Date payedAt) {
        this.payedAt = payedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.types
     *
     * @return the value of orders.types
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Byte getTypes() {
        return types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.types
     *
     * @param types the value for orders.types
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setTypes(Byte types) {
        this.types = types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customer_address_id
     *
     * @return the value of orders.customer_address_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getCustomerAddressId() {
        return customerAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customer_address_id
     *
     * @param customerAddressId the value for orders.customer_address_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setCustomerAddressId(Integer customerAddressId) {
        this.customerAddressId = customerAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.need_invoice
     *
     * @return the value of orders.need_invoice
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Boolean getNeedInvoice() {
        return needInvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.need_invoice
     *
     * @param needInvoice the value for orders.need_invoice
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setNeedInvoice(Boolean needInvoice) {
        this.needInvoice = needInvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.actual_price
     *
     * @return the value of orders.actual_price
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getActualPrice() {
        return actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.actual_price
     *
     * @param actualPrice the value for orders.actual_price
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setActualPrice(Integer actualPrice) {
        this.actualPrice = actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.front_money
     *
     * @return the value of orders.front_money
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getFrontMoney() {
        return frontMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.front_money
     *
     * @param frontMoney the value for orders.front_money
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setFrontMoney(Integer frontMoney) {
        this.frontMoney = frontMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.front_pay_status
     *
     * @return the value of orders.front_pay_status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Byte getFrontPayStatus() {
        return frontPayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.front_pay_status
     *
     * @param frontPayStatus the value for orders.front_pay_status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setFrontPayStatus(Byte frontPayStatus) {
        this.frontPayStatus = frontPayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pay_status
     *
     * @return the value of orders.pay_status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Byte getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pay_status
     *
     * @param payStatus the value for orders.pay_status
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setPayStatus(Byte payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.created_user_id
     *
     * @return the value of orders.created_user_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.created_user_id
     *
     * @param createdUserId the value for orders.created_user_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setCreatedUserId(Integer createdUserId) {
        this.createdUserId = createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.created_user_type
     *
     * @return the value of orders.created_user_type
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Byte getCreatedUserType() {
        return createdUserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.created_user_type
     *
     * @param createdUserType the value for orders.created_user_type
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setCreatedUserType(Byte createdUserType) {
        this.createdUserType = createdUserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.process_user_id
     *
     * @return the value of orders.process_user_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getProcessUserId() {
        return processUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.process_user_id
     *
     * @param processUserId the value for orders.process_user_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setProcessUserId(Integer processUserId) {
        this.processUserId = processUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.process_user_name
     *
     * @return the value of orders.process_user_name
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getProcessUserName() {
        return processUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.process_user_name
     *
     * @param processUserName the value for orders.process_user_name
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setProcessUserName(String processUserName) {
        this.processUserName = processUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.created_at
     *
     * @return the value of orders.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.created_at
     *
     * @param createdAt the value for orders.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.updated_at
     *
     * @return the value of orders.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.updated_at
     *
     * @param updatedAt the value for orders.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.agent_order_marks_id
     *
     * @return the value of orders.agent_order_marks_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getAgentOrderMarksId() {
        return agentOrderMarksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.agent_order_marks_id
     *
     * @param agentOrderMarksId the value for orders.agent_order_marks_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setAgentOrderMarksId(Integer agentOrderMarksId) {
        this.agentOrderMarksId = agentOrderMarksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.belongs_to
     *
     * @return the value of orders.belongs_to
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getBelongsTo() {
        return belongsTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.belongs_to
     *
     * @param belongsTo the value for orders.belongs_to
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setBelongsTo(Integer belongsTo) {
        this.belongsTo = belongsTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.invoice_type
     *
     * @return the value of orders.invoice_type
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getInvoiceType() {
        return invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.invoice_type
     *
     * @param invoiceType the value for orders.invoice_type
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setInvoiceType(Integer invoiceType) {
        this.invoiceType = invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.comment
     *
     * @return the value of orders.comment
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.comment
     *
     * @param comment the value for orders.comment
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.invoice_info
     *
     * @return the value of orders.invoice_info
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getInvoiceInfo() {
        return invoiceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.invoice_info
     *
     * @param invoiceInfo the value for orders.invoice_info
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setInvoiceInfo(String invoiceInfo) {
        this.invoiceInfo = invoiceInfo;
    }
}