package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class OrderLogistic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.order_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.logistics_name
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String logisticsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.logistics_number
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private String logisticsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logistics.cs_out_storage_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer csOutStorageId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.id
     *
     * @return the value of order_logistics.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.id
     *
     * @param id the value for order_logistics.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.order_id
     *
     * @return the value of order_logistics.order_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.order_id
     *
     * @param orderId the value for order_logistics.order_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.logistics_name
     *
     * @return the value of order_logistics.logistics_name
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getLogisticsName() {
        return logisticsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.logistics_name
     *
     * @param logisticsName the value for order_logistics.logistics_name
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setLogisticsName(String logisticsName) {
        this.logisticsName = logisticsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.logistics_number
     *
     * @return the value of order_logistics.logistics_number
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public String getLogisticsNumber() {
        return logisticsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.logistics_number
     *
     * @param logisticsNumber the value for order_logistics.logistics_number
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setLogisticsNumber(String logisticsNumber) {
        this.logisticsNumber = logisticsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.created_at
     *
     * @return the value of order_logistics.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.created_at
     *
     * @param createdAt the value for order_logistics.created_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.updated_at
     *
     * @return the value of order_logistics.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.updated_at
     *
     * @param updatedAt the value for order_logistics.updated_at
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logistics.cs_out_storage_id
     *
     * @return the value of order_logistics.cs_out_storage_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getCsOutStorageId() {
        return csOutStorageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logistics.cs_out_storage_id
     *
     * @param csOutStorageId the value for order_logistics.cs_out_storage_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setCsOutStorageId(Integer csOutStorageId) {
        this.csOutStorageId = csOutStorageId;
    }
}