package com.comdosoft.financial.manage.domain.zhangfu;

public class OtherRequirement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_requirements.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_requirements.title
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_requirements.templet_file_path
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String templetFilePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_requirements.pay_channel_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer payChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_requirements.types
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Byte types;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_requirements.description
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_requirements.id
     *
     * @return the value of other_requirements.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_requirements.id
     *
     * @param id the value for other_requirements.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_requirements.title
     *
     * @return the value of other_requirements.title
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_requirements.title
     *
     * @param title the value for other_requirements.title
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_requirements.templet_file_path
     *
     * @return the value of other_requirements.templet_file_path
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getTempletFilePath() {
        return templetFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_requirements.templet_file_path
     *
     * @param templetFilePath the value for other_requirements.templet_file_path
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setTempletFilePath(String templetFilePath) {
        this.templetFilePath = templetFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_requirements.pay_channel_id
     *
     * @return the value of other_requirements.pay_channel_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getPayChannelId() {
        return payChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_requirements.pay_channel_id
     *
     * @param payChannelId the value for other_requirements.pay_channel_id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setPayChannelId(Integer payChannelId) {
        this.payChannelId = payChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_requirements.types
     *
     * @return the value of other_requirements.types
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Byte getTypes() {
        return types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_requirements.types
     *
     * @param types the value for other_requirements.types
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setTypes(Byte types) {
        this.types = types;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_requirements.description
     *
     * @return the value of other_requirements.description
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_requirements.description
     *
     * @param description the value for other_requirements.description
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }
}