package com.comdosoft.financial.manage.domain.zhangfu;

public class PayChannelBillingCycle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_channel_billing_cycles.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_channel_billing_cycles.pay_channel_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer payChannelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_channel_billing_cycles.billing_cycles_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    private Integer billingCyclesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_channel_billing_cycles.id
     *
     * @return the value of pay_channel_billing_cycles.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_channel_billing_cycles.id
     *
     * @param id the value for pay_channel_billing_cycles.id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_channel_billing_cycles.pay_channel_id
     *
     * @return the value of pay_channel_billing_cycles.pay_channel_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getPayChannelId() {
        return payChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_channel_billing_cycles.pay_channel_id
     *
     * @param payChannelId the value for pay_channel_billing_cycles.pay_channel_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setPayChannelId(Integer payChannelId) {
        this.payChannelId = payChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_channel_billing_cycles.billing_cycles_id
     *
     * @return the value of pay_channel_billing_cycles.billing_cycles_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public Integer getBillingCyclesId() {
        return billingCyclesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_channel_billing_cycles.billing_cycles_id
     *
     * @param billingCyclesId the value for pay_channel_billing_cycles.billing_cycles_id
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    public void setBillingCyclesId(Integer billingCyclesId) {
        this.billingCyclesId = billingCyclesId;
    }
}