package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class SysMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_messages.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_messages.title
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_messages.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_messages.content
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_messages.id
     *
     * @return the value of sys_messages.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_messages.id
     *
     * @param id the value for sys_messages.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_messages.title
     *
     * @return the value of sys_messages.title
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_messages.title
     *
     * @param title the value for sys_messages.title
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_messages.created_at
     *
     * @return the value of sys_messages.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_messages.created_at
     *
     * @param createdAt the value for sys_messages.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_messages.content
     *
     * @return the value of sys_messages.content
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_messages.content
     *
     * @param content the value for sys_messages.content
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }
}