package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class SysShufflingFigure {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_shuffling_figures.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_shuffling_figures.picture_url
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String pictureUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_shuffling_figures.website_url
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private String websiteUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_shuffling_figures.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_shuffling_figures.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_shuffling_figures.id
     *
     * @return the value of sys_shuffling_figures.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_shuffling_figures.id
     *
     * @param id the value for sys_shuffling_figures.id
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_shuffling_figures.picture_url
     *
     * @return the value of sys_shuffling_figures.picture_url
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_shuffling_figures.picture_url
     *
     * @param pictureUrl the value for sys_shuffling_figures.picture_url
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_shuffling_figures.website_url
     *
     * @return the value of sys_shuffling_figures.website_url
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public String getWebsiteUrl() {
        return websiteUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_shuffling_figures.website_url
     *
     * @param websiteUrl the value for sys_shuffling_figures.website_url
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setWebsiteUrl(String websiteUrl) {
        this.websiteUrl = websiteUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_shuffling_figures.created_at
     *
     * @return the value of sys_shuffling_figures.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_shuffling_figures.created_at
     *
     * @param createdAt the value for sys_shuffling_figures.created_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_shuffling_figures.updated_at
     *
     * @return the value of sys_shuffling_figures.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_shuffling_figures.updated_at
     *
     * @param updatedAt the value for sys_shuffling_figures.updated_at
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}