package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.AgentGoodName;

public interface AgentGoodNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_good_names
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_good_names
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insert(AgentGoodName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_good_names
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insertSelective(AgentGoodName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_good_names
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    AgentGoodName selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_good_names
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKeySelective(AgentGoodName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_good_names
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKey(AgentGoodName record);
}