package com.comdosoft.financial.manage.mapper.zhangfu;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.comdosoft.financial.manage.domain.zhangfu.CsCancel;
import com.comdosoft.financial.manage.utils.page.PageRequest;

public interface CsCancelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_cancels
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_cancels
	 * @mbggenerated
	 */
	int insert(CsCancel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_cancels
	 * @mbggenerated
	 */
	CsCancel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_cancels
	 * @mbggenerated
	 */
	List<CsCancel> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_cancels
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CsCancel record);
	
	/**
	 * count records by keyword and status
	 * 
	 * @param status
	 *            the cs_cancels status
	 * @param keyword
	 *            the keyword to search for apply_num
	 */
	long countSelective(@Param("status") Integer status, @Param("keyword") String keyword);
	
	/**
	 * select page records by keyword and status
	 * 
	 * @param pageRequest
	 *            {@link PageRequest}
	 * @param status
	 *            the cs_cancels status
	 * @param keyword
	 *            the keyword to search for apply_num
	 */
	List<CsCancel> findPageSelective(
			@Param("pageRequest") PageRequest pageRequest,
			@Param("customerId") Integer customerId,
			@Param("status") Integer status, @Param("keyword") String keyword);
	
	/**
	 * select record info by primary key
	 * 
	 * @param id
	 *            primary key of cs_cancels
	 * @return
	 */
	CsCancel selectInfoByPrimaryKey(Integer id);
	
	/**
	 * dispatch process user by cs_cancel_ids
	 * 
	 * @param params
	 */
	void dispatchUserByIds(Map<String, Object> params);
}