package com.comdosoft.financial.manage.mapper.zhangfu;

import java.util.List;

import com.comdosoft.financial.manage.domain.zhangfu.CsLeaseReturnMark;

public interface CsLeaseReturnMarkMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_lease_return_marks
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_lease_return_marks
	 * @mbggenerated
	 */
	int insert(CsLeaseReturnMark record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_lease_return_marks
	 * @mbggenerated
	 */
	CsLeaseReturnMark selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_lease_return_marks
	 * @mbggenerated
	 */
	List<CsLeaseReturnMark> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_lease_return_marks
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CsLeaseReturnMark record);
	
	/**
	 * select marks by cs_lease_return_id
	 * 
	 * @param csLeaseId
	 * @return
	 */
	List<CsLeaseReturnMark> selectBycsLeaseId(Integer csLeaseId);
}