package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CsLeaseReturn;

public interface CsLeaseReturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_lease_returns
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_lease_returns
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insert(CsLeaseReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_lease_returns
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insertSelective(CsLeaseReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_lease_returns
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    CsLeaseReturn selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_lease_returns
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKeySelective(CsLeaseReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_lease_returns
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKey(CsLeaseReturn record);
}