package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CsRepair;

public interface CsRepairMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_repairs
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_repairs
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insert(CsRepair record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_repairs
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insertSelective(CsRepair record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_repairs
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    CsRepair selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_repairs
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKeySelective(CsRepair record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_repairs
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(CsRepair record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_repairs
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKey(CsRepair record);
}