package com.comdosoft.financial.manage.mapper.zhangfu;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.comdosoft.financial.manage.domain.zhangfu.CsReturn;
import com.comdosoft.financial.manage.utils.page.PageRequest;

public interface CsReturnMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_returns
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_returns
	 * @mbggenerated
	 */
	int insert(CsReturn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_returns
	 * @mbggenerated
	 */
	CsReturn selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_returns
	 * @mbggenerated
	 */
	List<CsReturn> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_returns
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CsReturn record);
	
	/**
	 * count records by keyword and status
	 * 
	 * @param status
	 *            the cs_returns status
	 * @param keyword
	 *            the keyword to search for apply_num
	 */
	long countSelective(@Param("status") Byte status, @Param("keyword") String keyword);
	
	/**
	 * select page records by keyword and status
	 * 
	 * @param pageRequest
	 *            {@link PageRequest}
	 * @param status
	 *            the cs_returns status
	 * @param keyword
	 *            the keyword to search for apply_num
	 */
	List<CsReturn> findPageSelective(
			@Param("pageRequest") PageRequest pageRequest,
			@Param("customerId") Integer customerId,
			@Param("status") Byte status, @Param("keyword") String keyword);
	
	/**
	 * select record info by primary key
	 * 
	 * @param id
	 *            primary key of cs_returns
	 * @return
	 */
	CsReturn selectInfoByPrimaryKey(Integer id);
	
	/**
	 * dispatch process user by cs_return_ids
	 * 
	 * @param params
	 */
	void dispatchUserByIds(Map<String, Object> params);
	
	int updateReturnPriceById(@Param("id") int id,@Param("addressId") int returnAddId,@Param("price") int price);
}