package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CsReceiverAddress;

public interface CsReceiverAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_receiver_addresses
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_receiver_addresses
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int insert(CsReceiverAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_receiver_addresses
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int insertSelective(CsReceiverAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_receiver_addresses
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    CsReceiverAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_receiver_addresses
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKeySelective(CsReceiverAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_receiver_addresses
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKey(CsReceiverAddress record);
}