package com.comdosoft.financial.manage.mapper.zhangfu;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.comdosoft.financial.manage.domain.zhangfu.CsRepair;
import com.comdosoft.financial.manage.utils.page.PageRequest;

public interface CsRepairMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_repairs
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_repairs
	 * @mbggenerated
	 */
	int insert(CsRepair record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_repairs
	 * @mbggenerated
	 */
	CsRepair selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_repairs
	 * @mbggenerated
	 */
	List<CsRepair> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_repairs
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CsRepair record);
	
	/**
	 * count records by keyword and status
	 * 
	 * @param status
	 *            the cs_repairs status
	 * @param keyword
	 *            the keyword to search for apply_num
	 */
	long countSelective(@Param("status") Byte status, @Param("keyword") String keyword);
	
	/**
	 * select page records by keyword and status
	 * 
	 * @param pageRequest
	 *            {@link PageRequest}
	 * @param status
	 *            the cs_repairs status
	 * @param keyword
	 *            the keyword to search for apply_num
	 */
	List<CsRepair> findPageSelective(
			@Param("pageRequest") PageRequest pageRequest,
			@Param("status") Byte status, @Param("keyword") String keyword);
	
	/**
	 * select record info by primary key
	 * 
	 * @param id
	 *            primary key of cs_repairs
	 * @return
	 */
	CsRepair selectInfoByPrimaryKey(Integer id);
	
	/**
	 * dispatch process user by cs_repair_ids
	 * 
	 * @param params
	 */
	void dispatchUserByIds(Map<String, Object> params);
}