package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CsUpdateInfoMark;

public interface CsUpdateInfoMarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_update_info_marks
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_update_info_marks
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int insert(CsUpdateInfoMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_update_info_marks
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int insertSelective(CsUpdateInfoMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_update_info_marks
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    CsUpdateInfoMark selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_update_info_marks
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKeySelective(CsUpdateInfoMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_update_info_marks
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(CsUpdateInfoMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_update_info_marks
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKey(CsUpdateInfoMark record);
}