package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CustomerIntegralConvert;
import com.comdosoft.financial.manage.domain.zhangfu.CustomerIntentionMark;
import com.comdosoft.financial.manage.utils.page.PageRequest;

import java.util.List;

public interface CustomerIntegralConvertMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_integral_converts
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_integral_converts
	 * @mbggenerated
	 */
	int insert(CustomerIntegralConvert record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_integral_converts
	 * @mbggenerated
	 */
	CustomerIntegralConvert selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_integral_converts
	 * @mbggenerated
	 */
	List<CustomerIntegralConvert> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_integral_converts
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CustomerIntegralConvert record);
	
	int count(Byte status, String keyword);

	List<CustomerIntegralConvert> findPage(PageRequest request, Byte status,
			String keyword);

	void updateStatus(CustomerIntegralConvert integralConvert);

	int insertMark(CustomerIntentionMark record);
	
	List<CustomerIntentionMark> selectMarksById(Integer id);
}