package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CustomerIntegralRecord;

public interface CustomerIntegralRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_integral_records
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_integral_records
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int insert(CustomerIntegralRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_integral_records
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int insertSelective(CustomerIntegralRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_integral_records
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    CustomerIntegralRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_integral_records
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKeySelective(CustomerIntegralRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_integral_records
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(CustomerIntegralRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_integral_records
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKey(CustomerIntegralRecord record);
}