package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CustomerAgentRelationMark;

public interface CustomerAgentRelationMarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_agent_relation_marks
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_agent_relation_marks
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int insert(CustomerAgentRelationMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_agent_relation_marks
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int insertSelective(CustomerAgentRelationMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_agent_relation_marks
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    CustomerAgentRelationMark selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_agent_relation_marks
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKeySelective(CustomerAgentRelationMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_agent_relation_marks
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKey(CustomerAgentRelationMark record);
}