package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CustomerIntention;
import com.comdosoft.financial.manage.domain.zhangfu.CustomerIntentionWithBLOBs;

public interface CustomerIntentionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_intentions
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_intentions
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int insert(CustomerIntentionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_intentions
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int insertSelective(CustomerIntentionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_intentions
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    CustomerIntentionWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_intentions
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKeySelective(CustomerIntentionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_intentions
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(CustomerIntentionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_intentions
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKey(CustomerIntention record);
}