package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.DictionaryBillingCycle;

public interface DictionaryBillingCycleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_billing_cycles
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_billing_cycles
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insert(DictionaryBillingCycle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_billing_cycles
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insertSelective(DictionaryBillingCycle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_billing_cycles
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    DictionaryBillingCycle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_billing_cycles
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKeySelective(DictionaryBillingCycle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_billing_cycles
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKey(DictionaryBillingCycle record);
}