package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.DictionaryReplaceReason;

public interface DictionaryReplaceReasonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_replace_reasons
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_replace_reasons
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int insert(DictionaryReplaceReason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_replace_reasons
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int insertSelective(DictionaryReplaceReason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_replace_reasons
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    DictionaryReplaceReason selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_replace_reasons
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKeySelective(DictionaryReplaceReason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_replace_reasons
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKey(DictionaryReplaceReason record);
}