package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.DictionaryOpenPrivateInfo;

public interface DictionaryOpenPrivateInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_open_private_infos
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_open_private_infos
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insert(DictionaryOpenPrivateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_open_private_infos
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insertSelective(DictionaryOpenPrivateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_open_private_infos
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    DictionaryOpenPrivateInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_open_private_infos
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKeySelective(DictionaryOpenPrivateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_open_private_infos
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(DictionaryOpenPrivateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_open_private_infos
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKey(DictionaryOpenPrivateInfo record);
}