package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.DictionaryCustomerOrderType;
import java.util.List;

public interface DictionaryCustomerOrderTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_customer_order_types
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_customer_order_types
     *
     * @mbggenerated
     */
    int insert(DictionaryCustomerOrderType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_customer_order_types
     *
     * @mbggenerated
     */
    DictionaryCustomerOrderType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_customer_order_types
     *
     * @mbggenerated
     */
    List<DictionaryCustomerOrderType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_customer_order_types
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DictionaryCustomerOrderType record);
}