package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.ExchangeGoodsRecord;

public interface ExchangeGoodsRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_goods_records
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_goods_records
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insert(ExchangeGoodsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_goods_records
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insertSelective(ExchangeGoodsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_goods_records
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    ExchangeGoodsRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_goods_records
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKeySelective(ExchangeGoodsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_goods_records
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(ExchangeGoodsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_goods_records
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKey(ExchangeGoodsRecord record);
}