package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.GoodsPicture;

public interface GoodsPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pictures
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pictures
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int insert(GoodsPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pictures
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int insertSelective(GoodsPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pictures
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    GoodsPicture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pictures
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKeySelective(GoodsPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_pictures
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKey(GoodsPicture record);
}