package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.GoodComment;

public interface GoodCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_comments
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_comments
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insert(GoodComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_comments
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insertSelective(GoodComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_comments
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    GoodComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_comments
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKeySelective(GoodComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_comments
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(GoodComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_comments
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKey(GoodComment record);
}