package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.Message_receiver;

public interface Message_receiverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_receivers
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_receivers
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int insert(Message_receiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_receivers
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int insertSelective(Message_receiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_receivers
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    Message_receiver selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_receivers
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKeySelective(Message_receiver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_receivers
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKey(Message_receiver record);
}