package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.Order;
import com.comdosoft.financial.manage.utils.page.PageRequest;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated
	 */
	int insert(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated
	 */
	Order selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated
	 */
	List<Order> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Order record);

	List<Order> findPageOrdersByKeys(@Param("pageRequest") PageRequest pageRequest,
			@Param("status") Byte status, @Param("keys") String keys,
			@Param("factoryId") Integer factoryId,@Param("types") List<Byte> types);
	
	long countByKeys(@Param("status") Byte status, @Param("keys") String keys,
			@Param("factoryId") Integer factoryId,@Param("types") List<Byte> types);
	
	Order findOrderInfo(Integer id);

	/**
	 * 第三方订单查询
	 * @param status
	 * @param keys
	 * @param customerId
	 * @return
	 */
	long countFactoryByKeys(@Param("status") Byte status, @Param("keys") String keys,
			@Param("customerId") Integer customerId);

	/**
	 * 第三方订单
	 * @param pageRequest
	 * @param status
	 * @param keys
	 * @param customerId
	 * @return
	 */
	List<Order> findFactoryPageOrdersByKeys(@Param("pageRequest") PageRequest pageRequest,
			@Param("status") Byte status, @Param("keys") String keys,
			@Param("customerId") Integer customerId);
}