package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.Order;
import java.util.List;

public interface OrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated
	 */
	int insert(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated
	 */
	Order selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated
	 */
	List<Order> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Order record);
}