package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.PosCategorie;
import java.util.List;

public interface PosCategorieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pos_categories
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pos_categories
     *
     * @mbggenerated
     */
    int insert(PosCategorie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pos_categories
     *
     * @mbggenerated
     */
    PosCategorie selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pos_categories
     *
     * @mbggenerated
     */
    List<PosCategorie> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pos_categories
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PosCategorie record);
}