package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.PrepareGoodRecord;

public interface PrepareGoodRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prepare_goods_records
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prepare_goods_records
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int insert(PrepareGoodRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prepare_goods_records
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int insertSelective(PrepareGoodRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prepare_goods_records
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    PrepareGoodRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prepare_goods_records
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKeySelective(PrepareGoodRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prepare_goods_records
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(PrepareGoodRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prepare_goods_records
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKey(PrepareGoodRecord record);
}