package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.SupportArea;

public interface SupportAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table support_areas
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table support_areas
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insert(SupportArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table support_areas
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insertSelective(SupportArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table support_areas
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    SupportArea selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table support_areas
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKeySelective(SupportArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table support_areas
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKey(SupportArea record);
}