package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.SysActivity;

public interface SysActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_activities
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_activities
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insert(SysActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_activities
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insertSelective(SysActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_activities
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    SysActivity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_activities
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKeySelective(SysActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_activities
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(SysActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_activities
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKey(SysActivity record);
}