package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.SysMessage;

public interface SysMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_messages
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_messages
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insert(SysMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_messages
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insertSelective(SysMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_messages
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    SysMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_messages
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKeySelective(SysMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_messages
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(SysMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_messages
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKey(SysMessage record);
}