package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.Terminal;
import java.util.List;

public interface TerminalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals
     *
     * @mbggenerated
     */
    int insert(Terminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals
     *
     * @mbggenerated
     */
    Terminal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals
     *
     * @mbggenerated
     */
    List<Terminal> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminals
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Terminal record);
}