package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.TerminalMark;

public interface TerminalMarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_marks
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_marks
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insert(TerminalMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_marks
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insertSelective(TerminalMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_marks
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    TerminalMark selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_marks
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKeySelective(TerminalMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_marks
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(TerminalMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_marks
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKey(TerminalMark record);
}