package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.TerminalTradeTypeInfo;

public interface TerminalTradeTypeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_trade_type_infos
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_trade_type_infos
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insert(TerminalTradeTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_trade_type_infos
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insertSelective(TerminalTradeTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_trade_type_infos
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    TerminalTradeTypeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_trade_type_infos
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKeySelective(TerminalTradeTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_trade_type_infos
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKey(TerminalTradeTypeInfo record);
}