package com.comdosoft.financial.manage.mapper.trades;

import com.comdosoft.financial.manage.domain.trades.GoodProfit;

public interface GoodProfitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_profits
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_profits
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insert(GoodProfit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_profits
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insertSelective(GoodProfit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_profits
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    GoodProfit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_profits
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKeySelective(GoodProfit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_profits
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKey(GoodProfit record);
}