package com.comdosoft.financial.manage.mapper.trades;

import java.util.List;

import com.comdosoft.financial.manage.domain.trades.TradeDayReport;

public interface TradeDayReportMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_day_reports
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_day_reports
	 * @mbggenerated
	 */
	int insert(TradeDayReport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_day_reports
	 * @mbggenerated
	 */
	TradeDayReport selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_day_reports
	 * @mbggenerated
	 */
	List<TradeDayReport> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_day_reports
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TradeDayReport record);
	
	List<TradeDayReport> selectLastWeek();
}