package com.comdosoft.financial.manage.mapper.trades;

import com.comdosoft.financial.manage.domain.trades.tradeTotalDayReport;

public interface tradeTotalDayReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_total_day_reports
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_total_day_reports
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int insert(tradeTotalDayReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_total_day_reports
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int insertSelective(tradeTotalDayReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_total_day_reports
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    tradeTotalDayReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_total_day_reports
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKeySelective(tradeTotalDayReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_total_day_reports
     *
     * @mbggenerated Thu Jan 29 14:22:32 CST 2015
     */
    int updateByPrimaryKey(tradeTotalDayReport record);
}