package com.comdosoft.financial.manage.mapper.trades;

import com.comdosoft.financial.manage.domain.trades.TradeTotalDayReport;

public interface TradeTotalDayReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_total_day_reports
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_total_day_reports
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insert(TradeTotalDayReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_total_day_reports
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insertSelective(TradeTotalDayReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_total_day_reports
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    TradeTotalDayReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_total_day_reports
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKeySelective(TradeTotalDayReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_total_day_reports
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKey(TradeTotalDayReport record);
}