package com.comdosoft.financial.manage.mapper.trades;

import com.comdosoft.financial.manage.domain.trades.TradeTransferRepaymentRecord;

public interface TradeTransferRepaymentRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transfer_repayment_records
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transfer_repayment_records
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insert(TradeTransferRepaymentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transfer_repayment_records
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int insertSelective(TradeTransferRepaymentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transfer_repayment_records
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    TradeTransferRepaymentRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transfer_repayment_records
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKeySelective(TradeTransferRepaymentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_transfer_repayment_records
     *
     * @mbggenerated Thu Jan 29 14:34:31 CST 2015
     */
    int updateByPrimaryKey(TradeTransferRepaymentRecord record);
}